import React, { useState, useEffect } from "react";
import Head from "next/head";
import explore from "../src/img/explore.svg";
import Image from "next/image";
import Link from "next/link";
import { AiOutlineSearch, AiFillPlusCircle } from "react-icons/ai";
import Movies from "../src/components/Movies";

const watchlist = () => {
  const [storedMovies, setStoredMovies] = useState([]);
  useEffect(() => {
    const storedMovies = JSON.parse(localStorage.getItem("storedMovies"));
    if (storedMovies) {
      setStoredMovies(storedMovies);
    }
  }, []);

  function removeWatchlist(e, id) {
    const removedMovie = storedMovies.filter((movie) => movie.imdbID !== id);
    localStorage.setItem("storedMovies", JSON.stringify(removedMovie));
    location.reload();
  }

  return (
    <>
      <div>
        <Head>
          <title>Movie Watchlist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex flex-col items-center">
          <div className="h-[200px] bg-hero bg-no-repeat bg-[center_top_-12rem] w-full md:bg-cover md:bg-[center_top_-40rem] md:h-[300px] lg:h-[400px] relative flex ">
            <div className="absolute w-full h-full bg-black/50"></div>
            <div className="flex md:max-w-[70%] justify-between lg:max-w-[35%] px-8 md:px-0 w-full absolute top-[50%] translate-y-[-50%] md:left-[50%] md:translate-x-[-50%] z-10 text-white">
              <div className="flex items-center justify-between md:justify-between w-full gap-8 md:gap-0 font md:px-8">
                <h1 className="text-3xl md:text-5xl font-roboto font-bold">
                  Watchlist
                </h1>
                <Link href="/">
                  <a className="text-xs md:text-xl font-roboto">Find movies</a>
                </Link>
              </div>
            </div>
          </div>

          <div className="h-[calc(100vh-200px)] md:h-[calc(100vh-300px)] lg:h-[calc(100vh-400px)] w-full flex flex-col items-center px-8">
            <div className="w-full h-full flex flex-col justify-start items-center gap-3 relative">
              {storedMovies.length ? (
                <Movies
                  dataMovie={storedMovies}
                  page={"watch"}
                  removeWatchlist={removeWatchlist}
                />
              ) : (
                <div className=" absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%] flex flex-col items-center justify-center ">
                  <h2 className="text-gray-400">
                    Your watchlist is looking a little empty...
                  </h2>
                  <Link href="/">
                    <a className="flex items-center gap-2">
                      <AiFillPlusCircle className="inline" size={20} />
                      Let's add some movies!
                    </a>
                  </Link>
                </div>
              )}
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default watchlist;
