import React from "react";
import Head from "next/head";
import explore from "../src/img/explore.svg";
import Image from "next/image";
import Link from "next/link";
import { AiOutlineSearch, AiFillPlusCircle } from "react-icons/ai";

const watchlist = () => {
  return (
    <>
      <div>
        <Head>
          <title>Movie Watchlist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex flex-col items-center">
          <div className="h-[200px] bg-hero bg-no-repeat bg-[center_top_-12rem] w-full relative flex">
            <div className="absolute w-full h-full bg-black/50"></div>
            <div className="px-8 w-full absolute top-[50%] translate-y-[-50%] z-10 text-white">
              <div className="flex items-center justify-between w-full gap-7 font">
                <h1 className="text-3xl font-roboto font-bold">
                  Find your film
                </h1>
                <Link href="/">
                  <a className="text-xs font-roboto">Search for movies</a>
                </Link>
              </div>
            </div>
          </div>

          <div className="h-[calc(100vh-200px)] w-full flex flex-col items-center px-8">
            <div className="h-full w-full flex flex-col justify-center items-center gap-3 -mt-5">
              <h2 className="text-gray-400">
                Your watchlist is looking a little empty...
              </h2>
              <Link href="/">
                <a className="flex items-center gap-2">
                  <AiFillPlusCircle className="inline" size={20} />
                  Let's add some movies!
                </a>
              </Link>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default watchlist;
